Us nav bar
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #10
Opened 2024-01-03 15:23 UTC by AntoPAA

2024-01-03 15:29 UTC, OlvMrn submitted a review, later dismissed

2024-01-03 15:35 UTC, aimach requested changes

2024-01-03 15:35 UTC, aimach commented on frontend/src/components/NavBar.css
le nom des classes ne respecte pas la nomenclature utilisée jusqu'ici
voir les autres fichiers css : .job-card

2024-01-04 16:44 UTC, jujuck requested changes, later dismissed

2024-01-04 16:44 UTC, jujuck commented on frontend/src/components/NavBar.jsx
> +        jobs
Une majuscule pour jobs

2024-01-05 09:37 UTC, aimach approved these changes

2024-01-05 09:39 UTC, OlvMrn approved these changes

2024-01-05 09:39 UTC, merged