rajout d'un carrousel page d'accueil
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #20
Opened 2024-01-17 13:10 UTC by AntoPAA

2024-01-17 13:18 UTC, OlvMrn approved these changes, later dismissed

2024-01-22 09:01 UTC, jujuck submitted a review, later dismissed

2024-01-22 09:01 UTC, jujuck commented on backend/src/router.js
> +router.get("/latestjobs", jobControllers.browseLatest);
L'url ne correspond pas à la convention REST
Tu peux faire une route /jobs/latests. Il faut mettre la route avant celle avec le params :id

2024-01-22 09:01 UTC, jujuck commented on frontend/src/components/JobCard.jsx
> +          <div className="job-card-type">{job.contract_type}</div>
Ne pas mettre de div, choisi plutot un h4,5,6, ou p. Balise sémantique

2024-01-22 09:01 UTC, jujuck commented on frontend/src/main.jsx
> +          const response = await connexion.get(`/latestjobs`);
Mets à jour ta route en fonction des modifs du backend

2024-01-22 09:01 UTC, jujuck commented on frontend/src/pages/HomePage.css
> +.barre-fleche-container {
What, une classe CSS en français.... Je m'en vais... C'est trop lol

2024-01-22 09:01 UTC, jujuck commented on frontend/src/pages/HomePage.jsx
> +      <h1 className="join-us">Nous Rejoindre</h1>
Pas de h1 après les h2 :arrow_up:

2024-01-22 15:38 UTC, iNaeRoZ approved these changes, later dismissed

2024-01-22 15:48 UTC, aimach requested changes

2024-01-22 15:48 UTC, aimach commented on backend/src/router.js
> +router.get("/jobs/latestjobs", jobControllers.browseLatest);
jobs/lastest

2024-01-22 15:48 UTC, aimach commented on frontend/src/main.jsx
> +          const response = await connexion.get(`/jobs/latestjobs`);
jobs/lastest

2024-01-22 15:48 UTC, aimach commented on frontend/src/pages/HomePage.jsx
> +          <h1>plus qu'un cabinet de recrutement informatique</h1>
il ne doit y avoir qu'un seul h1 dans votre application : pour moi ça serait "externatic". 
Et les autres ce sont des h2

2024-01-22 15:48 UTC, aimach commented on frontend/src/pages/HomePage.jsx
> +      <h1 className="join-us">Nous Rejoindre</h1>
plutôt un h2 du coup

2024-01-22 16:02 UTC, OlvMrn approved these changes

2024-01-22 16:19 UTC, aimach approved these changes

2024-01-22 16:19 UTC, merged