Feat onejob
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #28
Opened 2024-01-24 15:45 UTC by maahipticem

2024-01-24 15:51 UTC, iNaeRoZ submitted a review, later dismissed

2024-01-25 14:01 UTC, AntoPAA submitted a review, later dismissed

2024-01-25 14:01 UTC, AntoPAA commented on frontend/src/pages/consultant/ConsultantJobOffre.css
> +.consultantjoboffre {
les "-" entre les mots pour les classname

2024-01-25 14:01 UTC, AntoPAA commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +      <div className="consultantjoboffre">
pareil

2024-01-25 14:01 UTC, AntoPAA commented on frontend/src/public/Group 100.png
doublon ??

2024-01-25 14:54 UTC, aimach requested changes

2024-01-25 14:54 UTC, aimach commented on backend/src/models/JobManager.js
> +         job.company_id , job.consultant_id , job.id, job.title, job.description_mission, job.description_about_candidate, job.description_position, job.description_advantages, job.description_proces
les champs job.id et company.id doivent se mélanger dans le résultat de ta requête. Il faudrait leur donner un alias grâce à AS comme fait ci dessus. 
"job.id AS job_id"

2024-01-25 14:54 UTC, aimach commented on frontend/src/pages/Administration 2.jsx
renommer le fichier, ça ne devrait pas être avec " 2"

2024-01-25 14:54 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +        <div>{job.name}</div>
mettre une balise sémantique (h2, h3, etc. ou un p)

2024-01-25 14:54 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +          <div>Durée de travail : {job.contract_type}</div>
idem, mettre des balises sémantiques

2024-01-25 14:54 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +        <p>
une balise p n'encadre pas des balises div, c'est plutôt l'inverse !

2024-01-25 15:56 UTC, AntoPAA submitted a review, later dismissed

2024-01-25 16:17 UTC, aimach requested changes

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +        <div>Niveau de formation : {job.position_requirements}</div>
il faut une balise sémantique

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +        <div>Lieux : {job.location}</div>
il faut une balise sémantique

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +        <div>
nécessaire d'avoir une div autour du p ?

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +        <p>
pas de p qui englobe des div

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +          <div>Salaire : {job.salary}</div>
il faut une balise sémantique

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +          <div>Entrée en fonction : {job.starting_date}</div>
il faut une balise sémantique

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +          <div>CSP : {job.position_category}</div>
il faut une balise sémantique

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +          <div>Language : {job.language}</div>
il faut une balise sémantique

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +        <p>
pas de p qui englobe une div

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +            <div>{job.description_about_candidate}</div>
il faut une balise sémantique

2024-01-25 16:17 UTC, aimach commented on frontend/src/pages/consultant/ConsultantJobOffre.jsx
> +            Vous aurez notammnent en charge : <li>{job.description_mission}</li>
les li sont englobés par un ul

2024-01-26 08:36 UTC, iNaeRoZ submitted a review, later dismissed

2024-01-26 08:50 UTC, iNaeRoZ approved these changes

2024-01-26 09:01 UTC, aimach approved these changes

2024-01-26 09:01 UTC, merged