Admin consultants
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #36
Opened 2024-01-29 13:44 UTC by OlvMrn

2024-01-29 13:46 UTC, iNaeRoZ submitted a review, later dismissed

2024-01-29 13:54 UTC, iNaeRoZ submitted a review, later dismissed

2024-01-29 14:21 UTC, jujuck requested changes, later dismissed

2024-01-29 14:21 UTC, jujuck commented on backend/src/router.js
> +router.delete("/consultants/:id", userControllers.destroy);
check credentials

2024-02-05 11:33 UTC, AntoPAA submitted a review, later dismissed

2024-02-05 15:54 UTC, AntoPAA approved these changes, later dismissed
prions

2024-02-05 16:25 UTC, aimach requested changes

2024-02-05 16:25 UTC, aimach commented on backend/src/controllers/roleControllers.js
> +    const items = await tables.role.readAll();
changer "items"

2024-02-05 16:25 UTC, aimach commented on backend/src/controllers/roleControllers.js
> +    res.json(items);
manque le statut

2024-02-05 16:25 UTC, aimach commented on backend/src/controllers/roleControllers.js
> +    const item = await tables.role.read(req.params.id);
item...

2024-02-05 16:25 UTC, aimach commented on backend/src/controllers/roleControllers.js
> +    if (item == null) {
item...

2024-02-05 16:25 UTC, aimach commented on backend/src/controllers/roleControllers.js
> +      res.json(item);
manque le statut

2024-02-05 16:25 UTC, aimach commented on backend/src/controllers/roleControllers.js
> +  const item = req.body;
reprendre tout le fichier SVP

2024-02-05 16:25 UTC, aimach commented on backend/src/models/RoleManager.js
> +class ItemManager extends AbstractManager {
ItemManager ?

2024-02-05 16:25 UTC, aimach commented on backend/src/models/RoleManager.js
> +  async create(item) {
idem que pour le controller, changer item

2024-02-05 16:25 UTC, aimach commented on backend/src/models/RoleManager.js
> +      `insert into ${this.table} (title) values (?)`,
title ?

2024-02-05 16:25 UTC, aimach commented on backend/src/models/UserManager.js
> +        userData.id,
il faut utiliser le req.user.id

2024-02-05 16:25 UTC, aimach commented on frontend/src/components/card/AdminUserCard.jsx
> +          {element.firstname}prenom <br /> {element.lastname}nom <br />{" "}
enlever prenom et nom 
enlever l'espace à la fin

2024-02-05 16:25 UTC, aimach commented on backend/src/router.js
> +router.get("/roles", roleControllers.browse);
ne faudrait-il pas protéger cette route avec un check du rôle admin ?

2024-02-05 16:25 UTC, aimach commented on backend/src/router.js
> +router.get("/candidates", userControllers.getCandidates);
ne faudrait-il pas protéger cette route avec un check du rôle admin ?

2024-02-06 08:15 UTC, AntoPAA submitted a review, later dismissed

2024-02-06 08:46 UTC, maahipticem approved these changes

2024-02-06 08:48 UTC, aimach approved these changes

2024-02-06 08:49 UTC, merged