supression d'un job
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #38
Opened 2024-01-30 16:29 UTC by maahipticem

2024-01-30 16:35 UTC, iNaeRoZ approved these changes, later dismissed

2024-02-02 16:00 UTC, jujuck requested changes

2024-02-02 16:00 UTC, jujuck commented on backend/src/router.js
> +router.delete("/jobs/:id", jobControllers.destroy);
Besoin de vérifier le user et ses credentials (cookie)

2024-02-02 16:00 UTC, jujuck commented on frontend/src/main.jsx
> +                // element: <AdminJobDelete />,
Pas  de code mort en commentaire

2024-02-05 08:48 UTC, AntoPAA submitted a review, later dismissed

2024-02-05 09:05 UTC, jujuck requested changes

2024-02-05 09:05 UTC, jujuck commented on frontend/src/main.jsx
> +// import AdminJobDelete from "./pages/AdminJobDelete";
ligne morte

2024-02-05 09:05 UTC, jujuck commented on frontend/src/contexts/auth.jsx
> +  const [connected, setConnected] = useState({ role_id: 2 });
revenir à l'état précédent

2024-02-05 09:27 UTC, iNaeRoZ approved these changes, later dismissed

2024-02-05 10:09 UTC, jujuck submitted a review, later dismissed

2024-02-05 14:52 UTC, iNaeRoZ approved these changes, later dismissed

2024-02-05 16:36 UTC, aimach approved these changes

2024-02-06 08:18 UTC, AntoPAA approved these changes

2024-02-06 08:18 UTC, merged