rajout du bouton logout et quelque modif
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #50
Opened 2024-02-06 23:18 UTC by AntoPAA

2024-02-06 23:22 UTC, OlvMrn submitted a review, later dismissed

2024-02-07 07:56 UTC, jujuck requested changes

2024-02-07 07:56 UTC, jujuck commented on frontend/src/components/NavBar.jsx
> +      window.location.reload();
NON, pas de reload. Nettoie ton context

2024-02-07 16:10 UTC, maahipticem submitted a review, later dismissed

2024-02-07 16:34 UTC, jujuck approved these changes, later dismissed

2024-02-07 16:35 UTC, merged