consultant
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #7
Opened 2023-12-21 13:49 UTC by maahipticem

2023-12-21 15:51 UTC, AntoPAA approved these changes, later dismissed

2023-12-22 08:30 UTC, aimach requested changes

2023-12-22 08:30 UTC, aimach commented on backend/src/controllers/consultantControllers.js
> +const read = async (req, res, next) => {
à commenter si ce n'est pas implémenté

2023-12-22 08:30 UTC, aimach commented on backend/src/controllers/consultantControllers.js
> +const add = async (req, res, next) => {
à commenter si ce n'est pas implémenté

2023-12-22 08:30 UTC, aimach commented on backend/src/models/ConsultantManager.js
> +  async create(item) {
à commenter si ce n'est pas implémenté

2023-12-22 08:30 UTC, aimach commented on frontend/.eslintrc.json
> +    "react/prop-types": "off",
comme indiqué sur Discord, finalement pour le P3 on va utiliser les prop types. 
Donc il faudrait enlever cette ligne et faire le typage des props : on en discute quand tu veux !

2023-12-22 08:30 UTC, aimach commented on frontend/src/components/consultant/Consultant.jsx
je pense que ça ajouterait de la lisibilité dans ton code de nommer ce composant "ConsultatCard" sinon on ne sait pas trop ce qu'il y a dedans !

2023-12-22 11:02 UTC, AntoPAA submitted a review, later dismissed

2023-12-22 11:20 UTC, aimach requested changes

2023-12-22 11:20 UTC, aimach commented on package-lock.json
aaaaargh, il y a toujours la dépendance "install" 
----> vite un npm uninstall install en racine

2023-12-22 11:30 UTC, aimach approved these changes

2023-12-22 11:32 UTC, AntoPAA approved these changes

2024-01-03 08:26 UTC, merged