rajout du Footer + rajout sur toute les page + CSS responsive
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #8
Opened 2023-12-21 15:48 UTC by AntoPAA

2023-12-22 11:14 UTC, iNaeRoZ submitted a review, later dismissed

2023-12-22 11:29 UTC, aimach requested changes

2023-12-22 11:29 UTC, aimach commented on frontend/src/components/Footer.jsx
> +        <h2>Contact </h2>
pourquoi tout est en h2 ??

2023-12-22 11:29 UTC, aimach commented on frontend/src/components/Footer.jsx
> +        <h2>Externatic, cabinet de </h2>
pareil ??

2023-12-22 11:29 UTC, aimach commented on frontend/src/main.jsx
vous appelez Layout dans App donc vous pouvez laisser App.

2024-01-03 09:38 UTC, AntoPAA commented on frontend/src/components/Footer.jsx
> +        <h2>Contact </h2>
pourquoi modifier les h2 et pars quoi ?

2024-01-03 13:32 UTC, aimach approved these changes

2024-01-03 13:40 UTC, OlvMrn approved these changes

2024-01-03 13:40 UTC, merged