Feat@display all jobs
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic pull request #9
Opened 2023-12-22 11:13 UTC by OlvMrn

2023-12-22 11:14 UTC, AntoPAA submitted a review, later dismissed

2023-12-22 11:14 UTC, iNaeRoZ approved these changes, later dismissed

2023-12-22 11:42 UTC, aimach requested changes

2023-12-22 11:42 UTC, aimach commented on backend/database/schema.sql
> +INSERT INTO role (label) VALUES("candidat"),("consultant"),("admin");
doublon l.99

2023-12-22 11:42 UTC, aimach commented on backend/src/controllers/jobControllers.js
> +    res.json(jobs);
il manque le status

2023-12-22 11:42 UTC, aimach commented on backend/src/controllers/jobControllers.js
> +      res.json(job);
il manque le status

2023-12-22 11:42 UTC, aimach commented on backend/src/controllers/jobControllers.js
> +    if (job == null) {
job est un tableau, rempli ou vide. Il ne sera jamais null

2023-12-22 11:42 UTC, aimach commented on backend/src/models/JobManager.js
> +    // Execute the SQL INSERT query to add a new job to the "job" table
si ce n'est pas fonctionnel, à commenter

2023-12-22 11:42 UTC, aimach commented on frontend/src/components/AllJobs.jsx
> +  jobs: PropTypes.arrayOf(PropTypes.shape({})).isRequired,
il n'y a rien dans jobs ?

2023-12-22 11:42 UTC, aimach commented on frontend/src/pages/AllJobsPage.jsx
> +      <h1>Vos opportunités d'emploi</h1>
plutôt h2, voire h3

2024-01-03 08:28 UTC, AntoPAA submitted a review, later dismissed

2024-01-03 08:57 UTC, aimach approved these changes

2024-01-03 08:58 UTC, AntoPAA approved these changes

2024-01-03 08:59 UTC, merged